packages:
  - 'packages/**/*'
  - 'website'
  - 'playground'

catalog:
  # React
  react: "^19.2.6"
  react-dom: "^19.2.6"
  "@types/react": "^19.2.14"
  "@types/react-dom": "^19.2.3"

  # Build
  vite: "^6.3.5"
  "@vitejs/plugin-react": "^4.5.2"
  "vite-plugin-dts": "^4.5.4"
  "vite-plugin-lib-inject-css": "^2.2.2"
  typescript: "^5.9.3"

  # Test
  vitest: "^4.1.5"
  happy-dom: "^20.9.0"
